fastlane_version "2.6.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # carthage
  end

  desc "Run unit test and export to Reports/Test/"
  lane :test do
    scan(scheme: "SampleAppForCI", clean: true, code_coverage: true, device: "iPhone 6", output_directory: "Reports/Test/")
  end

  desc "Code Coverage"
  lane :code_coverage do
    slather(output_directory: "Reports/Code_Coverage", proj: "SampleAppForCI.xcodeproj", scheme: "SampleAppForCI", cobertura_xml: true, ignore: ["../*"])
  end

  desc "export archive and ipa"
  lane :export do |options|
    gym(
      project: "SampleAppForCI.xcodeproj",
      scheme: "SampleAppForCI",
      silent: true,
      clean: true,
      output_directory: "Export/"+options[:path], # Destination directory. Defaults to current directory.
      output_name: "SampleAppForCI.ipa",       # specify the name of the .ipa file to generate (including file extension)
      export_method: "enterprise",
      archive_path: "Export/SampleAppForCI.xcarchive"
      #sdk: "10.0"  # use SDK as the name or path of the base SDK when building the project.
    )
  end

end
